services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: ecommerce_backend
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: ecommerce-backend
    ports:
      - "9000:9000"
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/ecommerce_backend
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 9000 --reload

  redis:
    image: redis:7-alpine
    container_name: ecommerce_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: